[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start"

[cache]
paths = [
  "node_modules/.cache",
  ".next/cache"
]
